###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: myapp-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8082:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: myapp-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    neo4j:
      container_name: myapp-neo4j
      ports:
          - "7474:7474"
          - "7687:7687"
      volumes:
          - './neo4j/data:/data'
          - './neo4j/logs:/logs'
          - './neo4j/import:/var/lib/neo4j/import'
          - './neo4j/plugins:/plugins'
      environment:
          - NEO4J_AUTH=neo4j/myapppass
      image: 'neo4j:latest'

