FROM phpdockerio/php72-fpm:latest
WORKDIR "/application"

FROM phpdockerio/php72-fpm:latest
WORKDIR "/application"

# Install git
RUN apt-get update \
    && apt-get -y install git \
    && apt-get install php7.2-bcmath